# Generated by Django 5.0.6 on 2025-05-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='street_name',
        ),
    ]
