<<<<<<< HEAD
# Generated by Django 5.0.6 on 2025-05-09 12:01
=======
# Generated by Django 5.2 on 2025-05-09 12:09
>>>>>>> 42409dfefb6f2fcb6e887be564ab9232989b5393

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('kutish', 'kutish'), ('tasdiqlangan', 'tasdiqlangan'), ('yakunlangan', 'yakunlangan'), ('bekor qilindi', 'bekor qilindi')], max_length=20),
        ),
    ]
