# Generated by Django 5.0.6 on 2025-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=55, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('client', 'client'), ('usta', 'usta'), ('superuser', 'superuser')], default='client', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_get', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_get', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
